apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-app-staging
  namespace: argocd
  labels:
    environment: staging
    team: sre
spec:
  project: sre-project
  source:
    repoURL: https://github.com/rsergio07/sre-gitops-deployments
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10
