apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-app
  namespace: argocd
spec:
  project: sre-project
  source:
    repoURL: https://github.com/rsergio07/sre-abc-training
    targetRevision: main
    path: exercises/exercise10
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
