apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sre-project
  namespace: argocd
spec:
  description: SRE ABC Training Project
  sourceRepos:
    - https://github.com/rsergio07/sre-abc-training
  destinations:
    - namespace: application
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
